import {
  BedrockImageGenerationResponse,
  ConverseInferenceParams,
  GenerateImageParams,
  GenerateVideoParams,
  Model,
  StreamingChunk,
  StabilityAI2024ModelResponse,
  UnrecordedMessage,
  UsecaseConverseInferenceParams,
} from 'generative-ai-use-cases';
import {
  ConverseCommandInput,
  ConverseCommandOutput,
  ConverseStreamCommandInput,
  ConverseStreamOutput,
} from '@aws-sdk/client-bedrock-runtime';
import {
  CLAUDE_3_5_DEFAULT_PARAMS,
  CLAUDE_DEFAULT_PARAMS,
  CLAUDE_OPUS_4_5_DEFAULT_PARAMS,
  CLAUDE_OPUS_4_6_DEFAULT_PARAMS,
  CLAUDE_OPUS_4_DEFAULT_PARAMS,
  CLAUDE_SONNET_4_6_DEFAULT_PARAMS,
  CLAUDE_SONNET_4_DEFAULT_PARAMS,
  COMMANDR_DEFAULT_PARAMS,
  createBodyImageAmazonAdvancedImage,
  createBodyImageAmazonGeneralImage,
  createBodyImageStabilityAI2024Model,
  createBodyImageStableDiffusion,
  createBodyVideoLumaRayV2,
  createBodyVideoNovaReel,
  createBodyVideoNovaReelV11,
  createConverseCommandInput,
  createConverseCommandInputWithoutSystemContext,
  createConverseStreamCommandInput,
  createConverseStreamCommandInputWithoutSystemContext,
  DEEPSEEK_DEFAULT_PARAMS,
  DEFAULT_128K_DEFAULT_PARAMS,
  DEFAULT_64K_DEFAULT_PARAMS,
  LLAMA_DEFAULT_PARAMS,
  MISTRAL_DEFAULT_PARAMS,
  MIXTRAL_DEFAULT_PARAMS,
  NOVA_2_DEFAULT_PARAMS,
  NOVA_DEFAULT_PARAMS,
  OPENAI_DEFAULT_PARAMS,
  PALMYRA_DEFAULT_PARAMS,
  QWEN_16K_DEFAULT_PARAMS,
  QWEN_192K_DEFAULT_PARAMS,
  QWEN_64K_DEFAULT_PARAMS,
  TITAN_TEXT_DEFAULT_PARAMS,
  USECASE_DEFAULT_PARAMS,
} from './request-builders';
import {
  extractConverseOutput,
  extractConverseStreamOutput,
  extractOutputImageAmazonImage,
  extractOutputImageStabilityAI2024Model,
  extractOutputImageStableDiffusion,
} from './output-extractors';

// Definition of parameters and functions for each model related to text generation

export const BEDROCK_TEXT_GEN_MODELS: {
  [key: string]: {
    defaultParams: ConverseInferenceParams;
    usecaseParams: UsecaseConverseInferenceParams;
    createConverseCommandInput: (
      messages: UnrecordedMessage[],
      id: string,
      model: Model,
      defaultParams: ConverseInferenceParams,
      usecaseParams: UsecaseConverseInferenceParams
    ) => ConverseCommandInput;
    createConverseStreamCommandInput: (
      messages: UnrecordedMessage[],
      id: string,
      model: Model,
      defaultParams: ConverseInferenceParams,
      usecaseParams: UsecaseConverseInferenceParams
    ) => ConverseStreamCommandInput;
    extractConverseOutput: (body: ConverseCommandOutput) => StreamingChunk;
    extractConverseStreamOutput: (body: ConverseStreamOutput) => StreamingChunk;
  };
} = {
  'global.anthropic.claude-opus-4-6-v1': {
    defaultParams: CLAUDE_OPUS_4_6_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'us.anthropic.claude-opus-4-6-v1': {
    defaultParams: CLAUDE_OPUS_4_6_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'au.anthropic.claude-opus-4-6-v1': {
    defaultParams: CLAUDE_OPUS_4_6_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'eu.anthropic.claude-opus-4-6-v1': {
    defaultParams: CLAUDE_OPUS_4_6_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'global.anthropic.claude-sonnet-4-6': {
    defaultParams: CLAUDE_SONNET_4_6_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'us.anthropic.claude-sonnet-4-6': {
    defaultParams: CLAUDE_SONNET_4_6_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'eu.anthropic.claude-sonnet-4-6': {
    defaultParams: CLAUDE_SONNET_4_6_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'au.anthropic.claude-sonnet-4-6': {
    defaultParams: CLAUDE_SONNET_4_6_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'jp.anthropic.claude-sonnet-4-6': {
    defaultParams: CLAUDE_SONNET_4_6_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'us.anthropic.claude-opus-4-5-20251101-v1:0': {
    defaultParams: CLAUDE_OPUS_4_5_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'us.anthropic.claude-opus-4-1-20250805-v1:0': {
    defaultParams: CLAUDE_OPUS_4_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'us.anthropic.claude-opus-4-20250514-v1:0': {
    defaultParams: CLAUDE_OPUS_4_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'global.anthropic.claude-opus-4-5-20251101-v1:0': {
    defaultParams: CLAUDE_OPUS_4_5_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'global.anthropic.claude-sonnet-4-5-20250929-v1:0': {
    defaultParams: CLAUDE_SONNET_4_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'us.anthropic.claude-sonnet-4-5-20250929-v1:0': {
    defaultParams: CLAUDE_SONNET_4_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'eu.anthropic.claude-sonnet-4-5-20250929-v1:0': {
    defaultParams: CLAUDE_SONNET_4_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'jp.anthropic.claude-sonnet-4-5-20250929-v1:0': {
    defaultParams: CLAUDE_SONNET_4_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'global.anthropic.claude-haiku-4-5-20251001-v1:0': {
    defaultParams: CLAUDE_SONNET_4_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'us.anthropic.claude-haiku-4-5-20251001-v1:0': {
    defaultParams: CLAUDE_SONNET_4_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'eu.anthropic.claude-haiku-4-5-20251001-v1:0': {
    defaultParams: CLAUDE_SONNET_4_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'jp.anthropic.claude-haiku-4-5-20251001-v1:0': {
    defaultParams: CLAUDE_SONNET_4_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'global.anthropic.claude-sonnet-4-20250514-v1:0': {
    defaultParams: CLAUDE_SONNET_4_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'us.anthropic.claude-sonnet-4-20250514-v1:0': {
    defaultParams: CLAUDE_SONNET_4_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'eu.anthropic.claude-sonnet-4-20250514-v1:0': {
    defaultParams: CLAUDE_SONNET_4_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'apac.anthropic.claude-sonnet-4-20250514-v1:0': {
    defaultParams: CLAUDE_SONNET_4_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'anthropic.claude-3-5-sonnet-20241022-v2:0': {
    defaultParams: CLAUDE_3_5_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'us.anthropic.claude-3-5-sonnet-20241022-v2:0': {
    defaultParams: CLAUDE_3_5_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'apac.anthropic.claude-3-5-sonnet-20241022-v2:0': {
    defaultParams: CLAUDE_3_5_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'anthropic.claude-3-5-haiku-20241022-v1:0': {
    defaultParams: CLAUDE_3_5_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'us.anthropic.claude-3-7-sonnet-20250219-v1:0': {
    defaultParams: CLAUDE_SONNET_4_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'eu.anthropic.claude-3-7-sonnet-20250219-v1:0': {
    defaultParams: CLAUDE_SONNET_4_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'apac.anthropic.claude-3-7-sonnet-20250219-v1:0': {
    defaultParams: CLAUDE_SONNET_4_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'us.anthropic.claude-3-5-haiku-20241022-v1:0': {
    defaultParams: CLAUDE_3_5_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'anthropic.claude-3-5-sonnet-20240620-v1:0': {
    defaultParams: CLAUDE_3_5_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'us.anthropic.claude-3-5-sonnet-20240620-v1:0': {
    defaultParams: CLAUDE_3_5_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'eu.anthropic.claude-3-5-sonnet-20240620-v1:0': {
    defaultParams: CLAUDE_3_5_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'apac.anthropic.claude-3-5-sonnet-20240620-v1:0': {
    defaultParams: CLAUDE_3_5_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'anthropic.claude-3-opus-20240229-v1:0': {
    defaultParams: CLAUDE_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'us.anthropic.claude-3-opus-20240229-v1:0': {
    defaultParams: CLAUDE_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'anthropic.claude-3-sonnet-20240229-v1:0': {
    defaultParams: CLAUDE_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'us.anthropic.claude-3-sonnet-20240229-v1:0': {
    defaultParams: CLAUDE_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'eu.anthropic.claude-3-sonnet-20240229-v1:0': {
    defaultParams: CLAUDE_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'apac.anthropic.claude-3-sonnet-20240229-v1:0': {
    defaultParams: CLAUDE_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'anthropic.claude-3-haiku-20240307-v1:0': {
    defaultParams: CLAUDE_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'us.anthropic.claude-3-haiku-20240307-v1:0': {
    defaultParams: CLAUDE_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'eu.anthropic.claude-3-haiku-20240307-v1:0': {
    defaultParams: CLAUDE_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'apac.anthropic.claude-3-haiku-20240307-v1:0': {
    defaultParams: CLAUDE_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'amazon.titan-text-express-v1': {
    defaultParams: TITAN_TEXT_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInputWithoutSystemContext,
    createConverseStreamCommandInput:
      createConverseStreamCommandInputWithoutSystemContext,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'amazon.titan-text-premier-v1:0': {
    defaultParams: TITAN_TEXT_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInputWithoutSystemContext,
    createConverseStreamCommandInput:
      createConverseStreamCommandInputWithoutSystemContext,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'meta.llama3-8b-instruct-v1:0': {
    defaultParams: LLAMA_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'meta.llama3-70b-instruct-v1:0': {
    defaultParams: LLAMA_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'meta.llama3-1-8b-instruct-v1:0': {
    defaultParams: LLAMA_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'meta.llama3-1-70b-instruct-v1:0': {
    defaultParams: LLAMA_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'meta.llama3-1-405b-instruct-v1:0': {
    defaultParams: LLAMA_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'us.meta.llama3-2-1b-instruct-v1:0': {
    defaultParams: LLAMA_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'us.meta.llama3-2-3b-instruct-v1:0': {
    defaultParams: LLAMA_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'us.meta.llama3-2-11b-instruct-v1:0': {
    defaultParams: LLAMA_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'us.meta.llama3-2-90b-instruct-v1:0': {
    defaultParams: LLAMA_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'us.meta.llama3-3-70b-instruct-v1:0': {
    defaultParams: LLAMA_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'us.meta.llama4-scout-17b-instruct-v1:0': {
    defaultParams: LLAMA_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'us.meta.llama4-maverick-17b-instruct-v1:0': {
    defaultParams: LLAMA_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'mistral.mistral-7b-instruct-v0:2': {
    defaultParams: MISTRAL_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInputWithoutSystemContext,
    createConverseStreamCommandInput:
      createConverseStreamCommandInputWithoutSystemContext,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'mistral.mixtral-8x7b-instruct-v0:1': {
    defaultParams: MIXTRAL_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInputWithoutSystemContext,
    createConverseStreamCommandInput:
      createConverseStreamCommandInputWithoutSystemContext,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'mistral.mistral-small-2402-v1:0': {
    defaultParams: MISTRAL_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'mistral.mistral-large-2402-v1:0': {
    defaultParams: MISTRAL_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'mistral.mistral-large-2407-v1:0': {
    defaultParams: MISTRAL_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'us.mistral.pixtral-large-2502-v1:0': {
    defaultParams: MISTRAL_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'eu.mistral.pixtral-large-2502-v1:0': {
    defaultParams: MISTRAL_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'mistral.mistral-large-3-675b-instruct': {
    defaultParams: DEFAULT_128K_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'mistral.ministral-3-3b-instruct': {
    defaultParams: DEFAULT_128K_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'mistral.ministral-3-8b-instruct': {
    defaultParams: DEFAULT_128K_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'mistral.ministral-3-14b-instruct': {
    defaultParams: DEFAULT_128K_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'mistral.magistral-small-2509': {
    defaultParams: DEFAULT_64K_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'cohere.command-r-v1:0': {
    defaultParams: COMMANDR_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'cohere.command-r-plus-v1:0': {
    defaultParams: COMMANDR_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },

  'amazon.nova-pro-v1:0': {
    defaultParams: NOVA_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'amazon.nova-lite-v1:0': {
    defaultParams: NOVA_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'amazon.nova-micro-v1:0': {
    defaultParams: NOVA_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'us.amazon.nova-premier-v1:0': {
    defaultParams: NOVA_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'us.amazon.nova-pro-v1:0': {
    defaultParams: NOVA_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'us.amazon.nova-lite-v1:0': {
    defaultParams: NOVA_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'us.amazon.nova-micro-v1:0': {
    defaultParams: NOVA_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'us.amazon.nova-2-lite-v1:0': {
    defaultParams: NOVA_2_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'eu.amazon.nova-pro-v1:0': {
    defaultParams: NOVA_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'eu.amazon.nova-lite-v1:0': {
    defaultParams: NOVA_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'eu.amazon.nova-micro-v1:0': {
    defaultParams: NOVA_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'apac.amazon.nova-pro-v1:0': {
    defaultParams: NOVA_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'apac.amazon.nova-lite-v1:0': {
    defaultParams: NOVA_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'apac.amazon.nova-micro-v1:0': {
    defaultParams: NOVA_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'jp.amazon.nova-2-lite-v1:0': {
    defaultParams: NOVA_2_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'global.amazon.nova-2-lite-v1:0': {
    defaultParams: NOVA_2_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'deepseek.v3-v1:0': {
    defaultParams: DEEPSEEK_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'us.deepseek.r1-v1:0': {
    defaultParams: DEEPSEEK_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'qwen.qwen3-235b-a22b-2507-v1:0': {
    defaultParams: QWEN_192K_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'qwen.qwen3-32b-v1:0': {
    defaultParams: QWEN_16K_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'qwen.qwen3-coder-480b-a35b-v1:0': {
    defaultParams: QWEN_64K_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'qwen.qwen3-coder-30b-a3b-v1:0': {
    defaultParams: QWEN_192K_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'qwen.qwen3-next-80b-a3b': {
    defaultParams: DEFAULT_128K_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'qwen.qwen3-vl-235b-a22b': {
    defaultParams: DEFAULT_128K_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  // Although Palmyra supports system context, the model seems work best without it.
  'us.writer.palmyra-x4-v1:0': {
    defaultParams: PALMYRA_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInputWithoutSystemContext,
    createConverseStreamCommandInput:
      createConverseStreamCommandInputWithoutSystemContext,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'us.writer.palmyra-x5-v1:0': {
    defaultParams: PALMYRA_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInputWithoutSystemContext,
    createConverseStreamCommandInput:
      createConverseStreamCommandInputWithoutSystemContext,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'openai.gpt-oss-120b-1:0': {
    defaultParams: OPENAI_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInputWithoutSystemContext,
    createConverseStreamCommandInput:
      createConverseStreamCommandInputWithoutSystemContext,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'openai.gpt-oss-20b-1:0': {
    defaultParams: OPENAI_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInputWithoutSystemContext,
    createConverseStreamCommandInput:
      createConverseStreamCommandInputWithoutSystemContext,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'google.gemma-3-4b-it': {
    defaultParams: DEFAULT_64K_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInputWithoutSystemContext,
    createConverseStreamCommandInput:
      createConverseStreamCommandInputWithoutSystemContext,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'google.gemma-3-12b-it': {
    defaultParams: DEFAULT_64K_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInputWithoutSystemContext,
    createConverseStreamCommandInput:
      createConverseStreamCommandInputWithoutSystemContext,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'google.gemma-3-27b-it': {
    defaultParams: DEFAULT_64K_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInputWithoutSystemContext,
    createConverseStreamCommandInput:
      createConverseStreamCommandInputWithoutSystemContext,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  // MiniMax AI
  'minimax.minimax-m2': {
    // Max output token set to 128K since context length 196K
    defaultParams: DEFAULT_128K_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInputWithoutSystemContext,
    createConverseStreamCommandInput:
      createConverseStreamCommandInputWithoutSystemContext,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  // Moonshot AI
  'moonshot.kimi-k2-thinking': {
    defaultParams: DEFAULT_128K_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInputWithoutSystemContext,
    createConverseStreamCommandInput:
      createConverseStreamCommandInputWithoutSystemContext,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  // NVIDIA
  'nvidia.nemotron-nano-9b-v2': {
    defaultParams: DEFAULT_64K_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInputWithoutSystemContext,
    createConverseStreamCommandInput:
      createConverseStreamCommandInputWithoutSystemContext,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'nvidia.nemotron-nano-12b-v2': {
    defaultParams: DEFAULT_64K_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInputWithoutSystemContext,
    createConverseStreamCommandInput:
      createConverseStreamCommandInputWithoutSystemContext,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'nvidia.nemotron-nano-3-30b': {
    defaultParams: DEFAULT_128K_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInputWithoutSystemContext,
    createConverseStreamCommandInput:
      createConverseStreamCommandInputWithoutSystemContext,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  // === Custom models (not in upstream GenU) ===
  // DeepSeek V3.2 - similar to deepseek.v3-v1:0
  'deepseek.v3.2': {
    defaultParams: DEEPSEEK_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  // MiniMax M2.1 - system context enabled (Claude-like prompting)
  'minimax.minimax-m2.1': {
    defaultParams: DEFAULT_128K_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  // Z.AI GLM 4.7 - system context enabled (Claude-like prompting)
  'zai.glm-4.7': {
    defaultParams: DEFAULT_128K_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  'zai.glm-4.7-flash': {
    defaultParams: DEFAULT_64K_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  // Moonshot Kimi K2.5 - system context enabled (Claude-like prompting)
  'moonshotai.kimi-k2.5': {
    defaultParams: DEFAULT_128K_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
  // Qwen3 Coder Next - similar to qwen.qwen3-next-80b-a3b
  'qwen.qwen3-coder-next': {
    defaultParams: DEFAULT_128K_DEFAULT_PARAMS,
    usecaseParams: USECASE_DEFAULT_PARAMS,
    createConverseCommandInput: createConverseCommandInput,
    createConverseStreamCommandInput: createConverseStreamCommandInput,
    extractConverseOutput: extractConverseOutput,
    extractConverseStreamOutput: extractConverseStreamOutput,
  },
};

// Definition of parameters and functions for each image generation model

export const BEDROCK_IMAGE_GEN_MODELS: {
  [key: string]: {
    createBodyImage: (params: GenerateImageParams) => string;
    extractOutputImage: (
      response: BedrockImageGenerationResponse | StabilityAI2024ModelResponse
    ) => string;
  };
} = {
  'stability.stable-diffusion-xl-v1': {
    createBodyImage: createBodyImageStableDiffusion,
    extractOutputImage: extractOutputImageStableDiffusion,
  },
  'stability.stable-image-core-v1:1': {
    createBodyImage: createBodyImageStabilityAI2024Model,
    extractOutputImage: extractOutputImageStabilityAI2024Model,
  },
  'stability.stable-image-ultra-v1:1': {
    createBodyImage: createBodyImageStabilityAI2024Model,
    extractOutputImage: extractOutputImageStabilityAI2024Model,
  },
  'stability.sd3-5-large-v1:0': {
    createBodyImage: createBodyImageStabilityAI2024Model,
    extractOutputImage: extractOutputImageStabilityAI2024Model,
  },
  'amazon.titan-image-generator-v1': {
    createBodyImage: createBodyImageAmazonGeneralImage,
    extractOutputImage: extractOutputImageAmazonImage,
  },
  'amazon.titan-image-generator-v2:0': {
    createBodyImage: createBodyImageAmazonAdvancedImage,
    extractOutputImage: extractOutputImageAmazonImage,
  },
  'amazon.nova-canvas-v1:0': {
    createBodyImage: createBodyImageAmazonAdvancedImage,
    extractOutputImage: extractOutputImageAmazonImage,
  },
};

export const BEDROCK_VIDEO_GEN_MODELS: {
  [key: string]: {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    createBodyVideo: (params: GenerateVideoParams) => any;
  };
} = {
  'amazon.nova-reel-v1:0': {
    createBodyVideo: createBodyVideoNovaReel,
  },
  'amazon.nova-reel-v1:1': {
    createBodyVideo: createBodyVideoNovaReelV11,
  },
  'luma.ray-v2:0': {
    createBodyVideo: createBodyVideoLumaRayV2,
  },
};
